### ISSUE TITLE
[Request] Expose key modifiers through API

### ISSUE THREAD

**Issue by SpaceWalkerRS** [Siphalor/amecs-api#13]
While it is possible to access them through the `IKeybinding` duck interface, this is marked as "internal" and should not be used. Ideally the `AmecsKeyBinding` class has a getter so that other mods can see the complete key binding. 

My use-case: I am adding keybind information to tooltips in my mod's GUI. If a user has the Amecs mod installed my mod needs to be able to see what modifiers a keybinding has so that the tooltip still displays correct information.

**Comment by SpaceWalkerRS** [comment]
It seems I mistakenly looked at the duck interface from nmuk instead of amecs. While the amecs duck interface is not in the api package, it is otherwise not marked as internal, so I assume it is good to use. Sorry for the inconvenience.

**Comment by Siphalor** [comment]
Hi, and thanks for the request :)

I could've sworn that this was somewhere in the public API already, but apparently it really isn't ^^
Classes that are in the `impl` package are less stable, even if not explicitly marked as internal.

Just adding it to `AmecsKeyBinding` may solve your problem, but I'd like to provide an API that allows to query for modifiers on Vanilla key bindings as well.
So I think the way to go is to add a static method for that to `KeyBindingUtils`.
