### ISSUE TITLE
Crash with 1.16.2

### ISSUE THREAD

**Issue by Leo40Git** [Siphalor/amecs-api#3]
Crash log: <https://pastebin.com/k40HqFBh>
Seems like a method got deleted here? `net.minecraft.client.util.InputUtil$Type.method_1446(Lnet/minecraft/client/util/InputUtil$Type;Ljava/lang/String;I)V`

**Comment by Siphalor** [comment]
Hm, I'm currently playing on a 1.16.2 server with Amecs 1.3.0+mc1.16.1 which embeds Amecs API 1.0.2+1.16-rc1 (same version that you use) and it works like a charm even in the dev env.
So sorry, but I can't reproduce that issue. The method you're referencing totally exists on 1.16.2 with the same signature.
It seems like the mod is not getting remapped in your project. Can you try deleting the remapped mod in `.gradle/loom-cache/remapped-mods/` and try to reimport the project?

**Comment by Leo40Git** [comment]
Managed to get the same crash after completely deleting the entire `loom-cache` folder.
Is it safe to blame JitPack here?

**Comment by Siphalor** [comment]
nope, since it's working for me ;)

**Comment by Siphalor** [comment]
Maybe you try importing the Amecs or Mouse Wheelie project and see if that works for you?

**Comment by Siphalor** [comment]
I fear this bug is related to SpongePowered/Mixin#431.
I'm gonna see if I can implement a workaround using Reflection or so.
